module.exports = {
  SP_SUPPLIERS_ADD_SUPPLIER : "CALL SP_SUPPLIERS_ADD_SUPPLIER(?,?,?,?,?,?,?)",
  SP_SUPPLIERS_UPDATE_SUPPLIER : "CALL SP_SUPPLIERS_UPDATE_SUPPLIER(?,?,?,?,?,?,?,?)",
  SP_SUPPLIERS_DEL_SUPPLIER : "CALL SP_SUPPLIERS_DEL_SUPPLIER(?,?)",
  SP_SUPPLIERS_ADD_BILL : "CALL SP_SUPPLIERS_ADD_BILL(?,?,?,?,?,?)",
  SP_SUPPLIERS_ADD_PRODUCT_TO_BILL : "CALL SP_SUPPLIERS_ADD_PRODUCT_TO_BILL(?,?,?,?)",
  SP_SUPPLIERS_UPDATE_PRODUCT_FROM_BILL : "CALL SP_SUPPLIERS_UPDATE_PRODUCT_FROM_BILL(?,?,?,?)",
  SP_SUPPLIERS_DEL_PRODUCT_FROM_BILL : "CALL SP_SUPPLIERS_DEL_PRODUCT_FROM_BILL(?,?,?)",
  SP_SUPPLIERS_GET_BY_STORE : "CALL SP_SUPPLIERS_GET_BY_STORE(?, ?, ?)",
  SP_SUPPLIERS_GET : "CALL SP_SUPPLIERS_GET(?, ?)",
  SP_SUPPLIERS_GET_ALL : "CALL SP_SUPPLIERS_GET_ALL(?, ?)",
  SP_BILLS_COST_GET : "CALL SP_BILLS_COST_GET(?, ?, ?, ?, ?)"
}