module.exports = {
  SQL_SP_BILLS_CREATE_BILL : "CALL SP_BILLS_CREATE_BILL(?, ?, ?, ?, ?)",
  SQL_SP_BILLS_ADD_PRODUCT_TO_BILL : "CALL SP_BILLS_ADD_PRODUCT_TO_BILL(?, ?, ?, ?, ?)",
  SQL_SP_BILLS_CHANGE_STATUS : "CALL SP_BILLS_CHANGE_STATUS(?, ?)",
  SQL_SP_BILLS_DEL_PRODUCT_FROM_BILL : "CALL SP_BILLS_DEL_PRODUCT_FROM_BILL(?, ?)",
  SQL_SP_BILLS_UPDATE_PRODUCT_FROM_BILL : "CALL SP_BILLS_UPDATE_PRODUCT_FROM_BILL(?, ?, ?, ?, ?)",
  SQL_SP_BILLS_FIND_BILL : "CALL SP_BILLS_FIND_BILL(?, ?)",
  SQL_SP_BILLS_GET_BILL : "CALL SP_BILLS_GET_BILL(?, ?)",
  SQL_SP_BILLS_GET_BY_STORE : "CALL SP_BILLS_GET_BY_STORE(?, ?, ?, ?, ?)",
  SQL_SP_BILLS_GET_BILL_DETAIL : "CALL SP_BILLS_GET_BILL_DETAIL(?, ?)",
  SQL_SP_BILLS_GET_OPEN_BILLS : "CALL SP_BILLS_GET_OPEN_BILLS(?, ?)"
}