module.exports = {
	SP_COSTS_ADD_COST : "CALL SP_COSTS_ADD_COST(?,?,?,?,?,?,?,?)",
	SP_COSTS_CATEGORIES_GET : "CALL SP_COSTS_CATEGORIES_GET()",
	SP_COSTS_STATUS_GET : "CALL SP_COSTS_STATUS_GET()",
	SP_COSTS_GET : "CALL SP_COSTS_GET(?,?,?,?,?)"
}