module.exports = {
  SQL_CHECK_PATH_ACCESS : "SELECT 1 FROM PATHS P INNER JOIN PATHS_ROLES PR ON(P.ID_PATH = PR.ID_PATH) INNER JOIN USERS_ROLES UR ON (UR.ID_ROLE = PR.ID_ROLE) INNER JOIN USERS U ON(UR.ID_USER = U.ID_USER) WHERE U.ID_USER = ? AND PATH=? LIMIT 1"
}